(function () {
  'use strict';

  // ═══════════════════════════════════════════════════════
  // a) Duplicate injection guard
  // ═══════════════════════════════════════════════════════
  if (window.__smaNavbarLoaded) return;

  // ═══════════════════════════════════════════════════════
  // b) Path detection
  // ═══════════════════════════════════════════════════════
  var isPages = window.location.pathname.includes('/pages/') || window.location.pathname.includes('/admincms/');
  var homeUrl = isPages ? '../index.html' : 'index.html';
  var pages = function (name) {
    return isPages ? './' + name : 'pages/' + name;
  };
  var imgLogo = isPages ? '../assets/logo.png' : 'assets/logo.png';
  var faviconUrl = isPages ? '../assets/logo.png' : 'assets/logo.png';

  // ═══════════════════════════════════════════════════════
  // c) Active page detection
  // ═══════════════════════════════════════════════════════
  var filename = window.location.pathname.split('/').pop().replace('.html', '') || 'index';

  var profilPages = ['sejarah', 'struktur-organisasi', 'tenaga-pendidik', 'sarana-prasarana', 'prestasi'];
  var akademikPages = ['kurikulum', 'program-unggulan'];
  var organisasiPages = ['osis', 'ospm', 'ekstrakurikuler'];
  var informasiPages = ['berita', 'galeri', 'info-psb'];

  var activeNav = null;
  if (profilPages.indexOf(filename) !== -1) activeNav = 'profil';
  else if (akademikPages.indexOf(filename) !== -1) activeNav = 'akademik';
  else if (organisasiPages.indexOf(filename) !== -1) activeNav = 'organisasi';
  else if (informasiPages.indexOf(filename) !== -1) activeNav = 'informasi';

  // ═══════════════════════════════════════════════════════
  // d) Inject Favicon
  // ═══════════════════════════════════════════════════════
  var favLink = document.createElement('link');
  favLink.rel = 'icon';
  favLink.type = 'image/png';
  favLink.href = faviconUrl;
  document.head.appendChild(favLink);

  // ═══════════════════════════════════════════════════════
  // e) Inject Font Awesome CDN
  // ═══════════════════════════════════════════════════════
  var faLink = document.createElement('link');
  faLink.rel = 'stylesheet';
  faLink.href = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css';
  faLink.crossOrigin = 'anonymous';
  faLink.referrerPolicy = 'no-referrer';
  document.head.appendChild(faLink);

  // ═══════════════════════════════════════════════════════
  // f) Global CSS
  // ═══════════════════════════════════════════════════════
  var globalStyle = document.createElement('style');
  globalStyle.id = 'sma-global-css';
  globalStyle.textContent = [
    ':root {',
    '  --primary: #059669;',
    '  --primary-dark: #047857;',
    '  --primary-darker: #065f46;',
    '  --primary-light: #d1fae5;',
    '  --primary-lighter: #ecfdf5;',
    '  --secondary: #10b981;',
    '  --accent: #f59e0b;',
    '  --white: #ffffff;',
    '  --gray-50: #f9fafb;',
    '  --gray-100: #f3f4f6;',
    '  --gray-200: #e5e7eb;',
    '  --gray-300: #d1d5db;',
    '  --gray-400: #9ca3af;',
    '  --gray-500: #6b7280;',
    '  --gray-600: #4b5563;',
    '  --gray-700: #374151;',
    '  --gray-800: #1f2937;',
    '  --gray-900: #111827;',
    '  --shadow: 0 1px 3px rgba(0,0,0,0.1);',
    '  --shadow-md: 0 4px 6px rgba(0,0,0,0.07);',
    '  --shadow-lg: 0 10px 15px rgba(0,0,0,0.1);',
    '  --shadow-xl: 0 20px 25px rgba(0,0,0,0.1);',
    '  --radius: 12px;',
    '  --radius-lg: 16px;',
    '}',
    '',
    '*, *::before, *::after {',
    '  box-sizing: border-box;',
    '  margin: 0;',
    '  padding: 0;',
    '}',
    '',
    'body {',
    "  font-family: 'Poppins', sans-serif;",
    '  line-height: 1.6;',
    '  color: var(--gray-700);',
    '  background: var(--white);',
    '  overflow-x: hidden;',
    '}',
    '',
    'html {',
    '  scroll-behavior: smooth;',
    '}',
    '',
    'img {',
    '  max-width: 100%;',
    '  height: auto;',
    '  display: block;',
    '}',
    '',
    'a {',
    '  text-decoration: none;',
    '  color: inherit;',
    '}',
    '',
    'ul {',
    '  list-style: none;',
    '}',
    '',
    '::selection {',
    '  background: var(--primary);',
    '  color: white;',
    '}',
    '',
    '::-webkit-scrollbar {',
    '  width: 8px;',
    '}',
    '',
    '::-webkit-scrollbar-track {',
    '  background: var(--gray-100);',
    '}',
    '',
    '::-webkit-scrollbar-thumb {',
    '  background: var(--primary);',
    '  border-radius: 4px;',
    '}',
    '',
    '::-webkit-scrollbar-thumb:hover {',
    '  background: var(--primary-dark);',
    '}',
    '',
    '.page-wrapper {',
    '  padding-top: 72px;',
    '  min-height: 100vh;',
    '}',
    '',
    '.container {',
    '  max-width: 1200px;',
    '  margin: 0 auto;',
    '  padding: 0 24px;',
    '  width: 100%;',
    '}',
    '',
    '.section {',
    '  padding: 80px 0;',
    '}',
    '',
    'h1 {',
    '  font-size: 2.5rem;',
    '  font-weight: 800;',
    '  line-height: 1.2;',
    '  color: var(--gray-900);',
    '}',
    '',
    'h2 {',
    '  font-size: 2rem;',
    '  font-weight: 700;',
    '  line-height: 1.25;',
    '}',
    '',
    'h3 {',
    '  font-size: 1.5rem;',
    '  font-weight: 600;',
    '  line-height: 1.3;',
    '}',
    '',
    'h4 {',
    '  font-size: 1.25rem;',
    '  font-weight: 600;',
    '}',
    '',
    'p {',
    '  margin-bottom: 1rem;',
    '}',
    '',
    '.section-badge {',
    '  display: inline-block;',
    '  background: var(--primary);',
    '  color: white;',
    '  padding: 6px 16px;',
    '  border-radius: 50px;',
    '  font-size: 0.8rem;',
    '  text-transform: uppercase;',
    '  letter-spacing: 0.5px;',
    '  margin-bottom: 12px;',
    '}',
    '',
    '.section-title {',
    '  font-size: 2rem;',
    '  font-weight: 700;',
    '  margin-bottom: 8px;',
    '  position: relative;',
    '  display: inline-block;',
    '}',
    '',
    '.section-title::after {',
    "  content: '';",
    '  position: absolute;',
    '  bottom: -8px;',
    '  left: 0;',
    '  width: 60px;',
    '  height: 4px;',
    '  border-radius: 2px;',
    '  background: linear-gradient(to right, var(--primary), var(--secondary));',
    '}',
    '',
    '.section-subtitle {',
    '  color: var(--gray-500);',
    '  max-width: 600px;',
    '  margin: 20px auto 0;',
    '}',
    '',
    '.page-header {',
    '  background: linear-gradient(135deg, var(--primary-darker), var(--primary), var(--secondary));',
    '  color: white;',
    '  padding: 80px 0 60px;',
    '  text-align: center;',
    '  position: relative;',
    '  overflow: hidden;',
    '}',
    '',
    '.page-header::before {',
    "  content: '';",
    '  position: absolute;',
    '  top: -50%;',
    '  left: -50%;',
    '  width: 200%;',
    '  height: 200%;',
    '  background:',
    '    radial-gradient(circle at 20% 50%, rgba(255,255,255,0.08) 0%, transparent 50%),',
    '    radial-gradient(circle at 80% 20%, rgba(255,255,255,0.05) 0%, transparent 40%),',
    '    radial-gradient(circle at 40% 80%, rgba(255,255,255,0.1) 0%, transparent 60%);',
    '  pointer-events: none;',
    '}',
    '',
    '.page-header h1 {',
    '  color: white;',
    '  font-size: 2.5rem;',
    '  margin-bottom: 8px;',
    '}',
    '',
    '.page-header p {',
    '  opacity: 0.85;',
    '  font-size: 1.1rem;',
    '}',
    '',
    '.breadcrumb {',
    '  margin-top: 16px;',
    '  display: flex;',
    '  gap: 8px;',
    '  justify-content: center;',
    '  font-size: 0.9rem;',
    '  opacity: 0.9;',
    '}',
    '',
    '.breadcrumb a {',
    '  color: white;',
    '  opacity: 0.8;',
    '}',
    '',
    '.breadcrumb a:hover {',
    '  opacity: 1;',
    '}',
    '',
    '.breadcrumb span {',
    '  opacity: 0.6;',
    '}',
    '',
    '.btn {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  padding: 12px 28px;',
    '  border-radius: var(--radius);',
    '  font-weight: 600;',
    '  font-size: 0.95rem;',
    '  cursor: pointer;',
    '  border: none;',
    '  transition: all 0.3s;',
    '  font-family: inherit;',
    '}',
    '',
    '.btn-primary {',
    '  background: var(--primary);',
    '  color: white;',
    '}',
    '',
    '.btn-primary:hover {',
    '  background: var(--primary-dark);',
    '  transform: translateY(-2px);',
    '  box-shadow: var(--shadow-lg);',
    '}',
    '',
    '.btn-secondary {',
    '  background: var(--gray-100);',
    '  color: var(--gray-700);',
    '}',
    '',
    '.btn-secondary:hover {',
    '  background: var(--gray-200);',
    '}',
    '',
    '.btn-outline {',
    '  background: transparent;',
    '  border: 2px solid var(--primary);',
    '  color: var(--primary);',
    '}',
    '',
    '.btn-outline:hover {',
    '  background: var(--primary);',
    '  color: white;',
    '}',
    '',
    '.btn-sm {',
    '  padding: 8px 18px;',
    '  font-size: 0.85rem;',
    '}',
    '',
    '.btn-lg {',
    '  padding: 16px 36px;',
    '  font-size: 1.05rem;',
    '}',
    '',
    '.card {',
    '  background: white;',
    '  border-radius: 16px;',
    '  box-shadow: var(--shadow-md);',
    '  overflow: hidden;',
    '  transition: all 0.3s ease;',
    '}',
    '',
    '.card:hover {',
    '  transform: translateY(-4px);',
    '  box-shadow: var(--shadow-xl);',
    '}',
    '',
    '.grid {',
    '  display: grid;',
    '  gap: 24px;',
    '}',
    '',
    '.grid-2 {',
    '  grid-template-columns: repeat(2, 1fr);',
    '}',
    '',
    '.grid-3 {',
    '  grid-template-columns: repeat(3, 1fr);',
    '}',
    '',
    '.grid-4 {',
    '  grid-template-columns: repeat(4, 1fr);',
    '}',
    '',
    '.flex {',
    '  display: flex;',
    '}',
    '',
    '.flex-center {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '}',
    '',
    '.flex-between {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '}',
    '',
    '.flex-wrap {',
    '  flex-wrap: wrap;',
    '}',
    '',
    '.flex-col {',
    '  flex-direction: column;',
    '}',
    '',
    '.text-center { text-align: center; }',
    '.text-left { text-align: left; }',
    '.text-primary { color: var(--primary); }',
    '.text-muted { color: var(--gray-500); }',
    '.text-sm { font-size: 0.875rem; }',
    '.text-lg { font-size: 1.125rem; }',
    '',
    '.badge {',
    '  display: inline-block;',
    '  padding: 4px 12px;',
    '  border-radius: 50px;',
    '  font-size: 0.75rem;',
    '  font-weight: 600;',
    '}',
    '',
    '.badge-primary {',
    '  background: var(--primary-light);',
    '  color: var(--primary-dark);',
    '}',
    '',
    '.badge-accent {',
    '  background: #fef3c7;',
    '  color: #92400e;',
    '}',
    '',
    '.badge-danger {',
    '  background: #fee2e2;',
    '  color: #991b1b;',
    '}',
    '',
    '.spinner {',
    '  width: 40px;',
    '  height: 40px;',
    '  border: 4px solid var(--gray-200);',
    '  border-top-color: var(--primary);',
    '  border-radius: 50%;',
    '  animation: spin 0.8s linear infinite;',
    '  margin: 40px auto;',
    '}',
    '',
    '.loading-spinner {',
    '  display: flex;',
    '  justify-content: center;',
    '  padding: 40px;',
    '}',
    '',
    '@keyframes fadeInUp {',
    '  from { opacity: 0; transform: translateY(30px); }',
    '  to { opacity: 1; transform: translateY(0); }',
    '}',
    '',
    '@keyframes slideUp {',
    '  from { opacity: 0; transform: translateY(50px); }',
    '  to { opacity: 1; transform: translateY(0); }',
    '}',
    '',
    '@keyframes spin {',
    '  from { transform: rotate(0deg); }',
    '  to { transform: rotate(360deg); }',
    '}',
    '',
    '@media (max-width: 1024px) {',
    '  h1 { font-size: 2rem; }',
    '  h2 { font-size: 1.75rem; }',
    '  .section { padding: 60px 0; }',
    '}',
    '',
    '@media (max-width: 992px) {',
    '  .grid-4 { grid-template-columns: repeat(2, 1fr); }',
    '  .grid-3 { grid-template-columns: repeat(2, 1fr); }',
    '  .grid-2 { grid-template-columns: 1fr; }',
    '  h1 { font-size: 1.875rem; }',
    '}',
    '',
    '@media (max-width: 768px) {',
    '  h1 { font-size: 1.75rem; }',
    '  h2 { font-size: 1.5rem; }',
    '  .section { padding: 50px 0; }',
    '  .grid-4, .grid-3, .grid-2 { grid-template-columns: 1fr; }',
    '  .container { padding: 0 16px; }',
    '  .page-header { padding: 60px 0 40px; }',
    '  .page-header h1 { font-size: 1.75rem; }',
    '}',
    '',
    '@media (max-width: 576px) {',
    '  .container { padding: 0 16px; }',
    '  .btn { padding: 10px 20px; }',
    '  h1 { font-size: 1.5rem; }',
    '  .section { padding: 40px 0; }',
    '}'
  ].join('\n');
  document.head.appendChild(globalStyle);

  // ═══════════════════════════════════════════════════════
  // g) Navbar CSS
  // ═══════════════════════════════════════════════════════
  var navbarStyle = document.createElement('style');
  navbarStyle.id = 'sma-navbar-css';
  navbarStyle.textContent = [
    '#main-navbar {',
    '  position: fixed;',
    '  top: 0;',
    '  left: 0;',
    '  right: 0;',
    '  height: 72px;',
    '  background: rgba(255,255,255,0.97);',
    '  backdrop-filter: blur(16px);',
    '  -webkit-backdrop-filter: blur(16px);',
    '  z-index: 1000;',
    '  transition: all 0.3s ease;',
    '}',
    '',
    '#main-navbar.navbar-scrolled {',
    '  height: 60px;',
    '  box-shadow: 0 2px 20px rgba(0,0,0,0.08);',
    '}',
    '',
    '.navbar-inner {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  max-width: 1200px;',
    '  margin: 0 auto;',
    '  padding: 0 24px;',
    '  height: 100%;',
    '}',
    '',
    '.navbar-brand {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 12px;',
    '  text-decoration: none;',
    '}',
    '',
    '.navbar-brand img {',
    '  height: 40px;',
    '  width: 40px;',
    '  object-fit: contain;',
    '}',
    '',
    '.navbar-brand-icon {',
    '  width: 40px;',
    '  height: 40px;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  background: linear-gradient(135deg, var(--primary), var(--primary-dark));',
    '  color: white;',
    '  border-radius: 10px;',
    '  font-size: 1.1rem;',
    '  flex-shrink: 0;',
    '}',
    '',
    '.navbar-brand-text {',
    '  font-size: 1.1rem;',
    '  font-weight: 700;',
    '  color: var(--gray-900);',
    '  line-height: 1.2;',
    '}',
    '',
    '.navbar-brand-text span {',
    '  display: block;',
    '  font-size: 0.7rem;',
    '  font-weight: 400;',
    '  color: var(--gray-500);',
    '}',
    '',
    '.navbar-menu {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 4px;',
    '}',
    '',
    '.nav-link {',
    '  padding: 8px 14px;',
    '  border-radius: 8px;',
    '  font-size: 0.9rem;',
    '  font-weight: 500;',
    '  color: var(--gray-700);',
    '  transition: all 0.2s;',
    '  cursor: pointer;',
    '  position: relative;',
    '}',
    '',
    '.nav-link:hover, .nav-link.active {',
    '  background: var(--primary-lighter);',
    '  color: var(--primary);',
    '}',
    '',
    '.nav-link.active::after {',
    "  content: '';",
    '  position: absolute;',
    '  bottom: 0;',
    '  left: 50%;',
    '  transform: translateX(-50%);',
    '  width: 20px;',
    '  height: 3px;',
    '  background: var(--primary);',
    '  border-radius: 2px;',
    '}',
    '',
    '.dropdown {',
    '  position: relative;',
    '}',
    '',
    '.dropdown-menu {',
    '  position: absolute;',
    '  top: 100%;',
    '  left: 0;',
    '  min-width: 220px;',
    '  background: white;',
    '  border-radius: 12px;',
    '  box-shadow: 0 10px 40px rgba(0,0,0,0.12);',
    '  padding: 8px;',
    '  opacity: 0;',
    '  visibility: hidden;',
    '  transform: translateY(10px);',
    '  transition: all 0.25s ease;',
    '  z-index: 100;',
    '}',
    '',
    '.dropdown:hover .dropdown-menu {',
    '  opacity: 1;',
    '  visibility: visible;',
    '  transform: translateY(0);',
    '}',
    '',
    '.dropdown-item {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  padding: 10px 14px;',
    '  border-radius: 8px;',
    '  font-size: 0.875rem;',
    '  color: var(--gray-700);',
    '  transition: all 0.2s;',
    '  cursor: pointer;',
    '}',
    '',
    '.dropdown-item:hover {',
    '  background: var(--primary-lighter);',
    '  color: var(--primary);',
    '  padding-left: 18px;',
    '}',
    '',
    '.dropdown-item i {',
    '  width: 18px;',
    '  text-align: center;',
    '  font-size: 0.8rem;',
    '  color: var(--primary);',
    '}',
    '',
    '.psb-btn {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 6px;',
    '  padding: 10px 22px;',
    '  background: linear-gradient(135deg, var(--primary), var(--primary-dark));',
    '  color: white;',
    '  border-radius: 50px;',
    '  font-size: 0.875rem;',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  transition: all 0.3s;',
    '  margin-left: 12px;',
    '  text-decoration: none;',
    '  border: none;',
    '}',
    '',
    '.psb-btn:hover {',
    '  transform: translateY(-2px);',
    '  box-shadow: 0 4px 15px rgba(5,150,105,0.4);',
    '  color: white;',
    '}',
    '',
    '.hamburger {',
    '  display: none;',
    '  flex-direction: column;',
    '  gap: 5px;',
    '  cursor: pointer;',
    '  padding: 8px;',
    '  background: none;',
    '  border: none;',
    '}',
    '',
    '.hamburger span {',
    '  width: 24px;',
    '  height: 2.5px;',
    '  background: var(--gray-700);',
    '  border-radius: 2px;',
    '  transition: all 0.3s;',
    '}',
    '',
    '.hamburger.active span:nth-child(1) {',
    '  transform: rotate(45deg) translate(5px, 5px);',
    '}',
    '',
    '.hamburger.active span:nth-child(2) {',
    '  opacity: 0;',
    '}',
    '',
    '.hamburger.active span:nth-child(3) {',
    '  transform: rotate(-45deg) translate(5px, -5px);',
    '}',
    '',
    '.mobile-overlay {',
    '  display: none;',
    '  position: fixed;',
    '  inset: 0;',
    '  background: rgba(0,0,0,0.5);',
    '  z-index: 998;',
    '  opacity: 0;',
    '  transition: opacity 0.3s;',
    '}',
    '',
    '.mobile-overlay.active {',
    '  display: block;',
    '  opacity: 1;',
    '}',
    '',
    '.mobile-menu {',
    '  position: fixed;',
    '  top: 0;',
    '  right: -300px;',
    '  width: 300px;',
    '  height: 100vh;',
    '  background: white;',
    '  z-index: 999;',
    '  transition: right 0.3s ease;',
    '  overflow-y: auto;',
    '  padding: 24px;',
    '}',
    '',
    '.mobile-menu.active {',
    '  right: 0;',
    '}',
    '',
    '.mobile-close {',
    '  position: absolute;',
    '  top: 16px;',
    '  right: 16px;',
    '  background: none;',
    '  border: none;',
    '  font-size: 1.5rem;',
    '  cursor: pointer;',
    '  color: var(--gray-700);',
    '}',
    '',
    '.mobile-menu .mobile-nav-link {',
    '  display: block;',
    '  padding: 12px 0;',
    '  font-size: 1rem;',
    '  font-weight: 500;',
    '  color: var(--gray-700);',
    '  border-bottom: 1px solid var(--gray-100);',
    '  cursor: pointer;',
    '}',
    '',
    '.mobile-dropdown-toggle {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  align-items: center;',
    '}',
    '',
    '.mobile-dropdown-toggle i.fa-chevron-down {',
    '  font-size: 0.75rem;',
    '  transition: transform 0.3s;',
    '}',
    '',
    '.mobile-submenu {',
    '  max-height: 0;',
    '  overflow: hidden;',
    '  transition: max-height 0.3s ease;',
    '}',
    '',
    '.mobile-submenu.active {',
    '  max-height: 500px;',
    '}',
    '',
    '.mobile-submenu a {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  padding: 10px 16px;',
    '  font-size: 0.9rem;',
    '  color: var(--gray-600);',
    '}',
    '',
    '@media (max-width: 992px) {',
    '  .navbar-menu { display: none; }',
    '  .psb-btn.desktop { display: none; }',
    '  .hamburger { display: flex; }',
    '}'
  ].join('\n');
  document.head.appendChild(navbarStyle);

  // ═══════════════════════════════════════════════════════
  // h) Navbar HTML injection (waits for DOM)
  // ═══════════════════════════════════════════════════════
  function injectNavbar() {
    var profilActive = activeNav === 'profil' ? ' active' : '';
    var akademikActive = activeNav === 'akademik' ? ' active' : '';
    var organisasiActive = activeNav === 'organisasi' ? ' active' : '';
    var informasiActive = activeNav === 'informasi' ? ' active' : '';

    var navbarHTML = [
      '<nav id="main-navbar">',
      '  <div class="navbar-inner">',
      '    <a href="' + homeUrl + '" class="navbar-brand">',
      '      <img src="' + imgLogo + '" alt="Logo SMA Plus Almunawwarah" style="height:40px;width:40px;object-fit:contain;border-radius:8px;">',
      '      <div class="navbar-brand-text">SMA Plus Almunawwarah<span>Boarding School Islami</span></div>',
      '    </a>',
      '    <div class="navbar-menu">',
      '      <a href="' + homeUrl + '" class="nav-link' + (filename === 'index' ? ' active' : '') + '">Beranda</a>',
      '      <div class="dropdown">',
      '        <div class="nav-link' + profilActive + '">Profil <i class="fa-solid fa-chevron-down" style="font-size:0.65rem;margin-left:4px"></i></div>',
      '        <div class="dropdown-menu">',
      '          <a href="' + pages('sejarah.html') + '" class="dropdown-item"><i class="fa-solid fa-clock-rotate-left"></i> Sejarah</a>',
      '          <a href="' + pages('struktur-organisasi.html') + '" class="dropdown-item"><i class="fa-solid fa-sitemap"></i> Struktur Organisasi</a>',
      '          <a href="' + pages('tenaga-pendidik.html') + '" class="dropdown-item"><i class="fa-solid fa-chalkboard-user"></i> Tenaga Pendidik</a>',
      '          <a href="' + pages('sarana-prasarana.html') + '" class="dropdown-item"><i class="fa-solid fa-building"></i> Sarana Prasarana</a>',
      '          <a href="' + pages('prestasi.html') + '" class="dropdown-item"><i class="fa-solid fa-trophy"></i> Prestasi</a>',
      '        </div>',
      '      </div>',
      '      <div class="dropdown">',
      '        <div class="nav-link' + akademikActive + '">Akademik <i class="fa-solid fa-chevron-down" style="font-size:0.65rem;margin-left:4px"></i></div>',
      '        <div class="dropdown-menu">',
      '          <a href="' + pages('kurikulum.html') + '" class="dropdown-item"><i class="fa-solid fa-book-open"></i> Kurikulum</a>',
      '          <a href="' + pages('program-unggulan.html') + '" class="dropdown-item"><i class="fa-solid fa-star"></i> Program Unggulan</a>',
      '        </div>',
      '      </div>',
      '      <div class="dropdown">',
      '        <div class="nav-link' + organisasiActive + '">Organisasi <i class="fa-solid fa-chevron-down" style="font-size:0.65rem;margin-left:4px"></i></div>',
      '        <div class="dropdown-menu">',
      '          <a href="' + pages('osis.html') + '" class="dropdown-item"><i class="fa-solid fa-users"></i> OSIS</a>',
      '          <a href="' + pages('ospm.html') + '" class="dropdown-item"><i class="fa-solid fa-handshake"></i> OSPM</a>',
      '          <a href="' + pages('ekstrakurikuler.html') + '" class="dropdown-item"><i class="fa-solid fa-futbol"></i> Ekstrakurikuler</a>',
      '        </div>',
      '      </div>',
      '      <div class="dropdown">',
      '        <div class="nav-link' + informasiActive + '">Informasi <i class="fa-solid fa-chevron-down" style="font-size:0.65rem;margin-left:4px"></i></div>',
      '        <div class="dropdown-menu">',
      '          <a href="https://smaplusalmunawwarahsmd.blogspot.com/" class="dropdown-item"><i class="fa-solid fa-newspaper"></i> Berita</a>',
      '          <a href="' + pages('galeri.html') + '" class="dropdown-item"><i class="fa-solid fa-images"></i> Galeri</a>',
      '          <a href="' + pages('info-psb.html') + '" class="dropdown-item"><i class="fa-solid fa-clipboard-list"></i> Info PSB</a>',
      '        </div>',
      '      </div>',
      '      <a href="' + pages('link-psb.html') + '" class="psb-btn desktop"><i class="fa-solid fa-pen-to-square"></i> PSB Online</a>',
      '    </div>',
      '    <button class="hamburger" id="hamburger-btn" aria-label="Menu">',
      '      <span></span>',
      '      <span></span>',
      '      <span></span>',
      '    </button>',
      '  </div>',
      '</nav>',
      '',
      '<div class="mobile-overlay" id="mobile-overlay"></div>',
      '',
      '<div class="mobile-menu" id="mobile-menu">',
      '  <button class="mobile-close" id="mobile-close" aria-label="Close menu">&times;</button>',
      '  <div style="margin-top:48px">',
      '    <a href="' + homeUrl + '" class="mobile-nav-link">Beranda</a>',
      '',
      '    <div class="mobile-dropdown">',
      '      <div class="mobile-nav-link mobile-dropdown-toggle' + profilActive + '" data-target="mobile-profil">',
      '        Profil <i class="fa-solid fa-chevron-down"></i>',
      '      </div>',
      '      <div class="mobile-submenu" id="mobile-profil">',
      '        <a href="' + pages('sejarah.html') + '"><i class="fa-solid fa-clock-rotate-left"></i> Sejarah</a>',
      '        <a href="' + pages('struktur-organisasi.html') + '"><i class="fa-solid fa-sitemap"></i> Struktur Organisasi</a>',
      '        <a href="' + pages('tenaga-pendidik.html') + '"><i class="fa-solid fa-chalkboard-user"></i> Tenaga Pendidik</a>',
      '        <a href="' + pages('sarana-prasarana.html') + '"><i class="fa-solid fa-building"></i> Sarana Prasarana</a>',
      '        <a href="' + pages('prestasi.html') + '"><i class="fa-solid fa-trophy"></i> Prestasi</a>',
      '      </div>',
      '    </div>',
      '',
      '    <div class="mobile-dropdown">',
      '      <div class="mobile-nav-link mobile-dropdown-toggle' + akademikActive + '" data-target="mobile-akademik">',
      '        Akademik <i class="fa-solid fa-chevron-down"></i>',
      '      </div>',
      '      <div class="mobile-submenu" id="mobile-akademik">',
      '        <a href="' + pages('kurikulum.html') + '"><i class="fa-solid fa-book-open"></i> Kurikulum</a>',
      '        <a href="' + pages('program-unggulan.html') + '"><i class="fa-solid fa-star"></i> Program Unggulan</a>',
      '      </div>',
      '    </div>',
      '',
      '    <div class="mobile-dropdown">',
      '      <div class="mobile-nav-link mobile-dropdown-toggle' + organisasiActive + '" data-target="mobile-organisasi">',
      '        Organisasi <i class="fa-solid fa-chevron-down"></i>',
      '      </div>',
      '      <div class="mobile-submenu" id="mobile-organisasi">',
      '        <a href="' + pages('osis.html') + '"><i class="fa-solid fa-users"></i> OSIS</a>',
      '        <a href="' + pages('ospm.html') + '"><i class="fa-solid fa-handshake"></i> OSPM</a>',
      '        <a href="' + pages('ekstrakurikuler.html') + '"><i class="fa-solid fa-futbol"></i> Ekstrakurikuler</a>',
      '      </div>',
      '    </div>',
      '',
      '    <div class="mobile-dropdown">',
      '      <div class="mobile-nav-link mobile-dropdown-toggle' + informasiActive + '" data-target="mobile-informasi">',
      '        Informasi <i class="fa-solid fa-chevron-down"></i>',
      '      </div>',
      '      <div class="mobile-submenu" id="mobile-informasi">',
      '        <a href="' + pages('berita.html') + '"><i class="fa-solid fa-newspaper"></i> Berita</a>',
      '        <a href="' + pages('galeri.html') + '"><i class="fa-solid fa-images"></i> Galeri</a>',
      '        <a href="' + pages('info-psb.html') + '"><i class="fa-solid fa-clipboard-list"></i> Info PSB</a>',
      '      </div>',
      '    </div>',
      '',
      '    <a href="' + pages('link-psb.html') + '" class="psb-btn" style="margin-top:20px;width:100%;justify-content:center;"><i class="fa-solid fa-pen-to-square"></i> PSB Online</a>',
      '  </div>',
      '</div>'
    ].join('\n');

    var wrapper = document.querySelector('.page-wrapper');
    if (wrapper) {
      wrapper.insertAdjacentHTML('afterbegin', navbarHTML);
    } else {
      document.body.insertAdjacentHTML('afterbegin', navbarHTML);
    }
  }

  // ═══════════════════════════════════════════════════════
  // i) JavaScript logic injection
  // ═══════════════════════════════════════════════════════
  function injectScript() {
    var script = document.createElement('script');
    script.textContent = [
      '(function() {',
      '  "use strict";',
      '',
      '  // Scroll handler – add/remove navbar-scrolled class',
      '  var navbar = document.getElementById("main-navbar");',
      '  var ticking = false;',
      '',
      '  function onScroll() {',
      '    if (!ticking) {',
      '      window.requestAnimationFrame(function() {',
      '        if (window.scrollY > 50) {',
      '          navbar.classList.add("navbar-scrolled");',
      '        } else {',
      '          navbar.classList.remove("navbar-scrolled");',
      '        }',
      '        ticking = false;',
      '      });',
      '      ticking = true;',
      '    }',
      '  }',
      '',
      '  window.addEventListener("scroll", onScroll, { passive: true });',
      '  onScroll();',
      '',
      '  // Mobile menu elements',
      '  var hamburger = document.getElementById("hamburger-btn");',
      '  var mobileOverlay = document.getElementById("mobile-overlay");',
      '  var mobileMenu = document.getElementById("mobile-menu");',
      '  var mobileClose = document.getElementById("mobile-close");',
      '',
      '  function openMobileMenu() {',
      '    hamburger.classList.add("active");',
      '    mobileOverlay.classList.add("active");',
      '    mobileMenu.classList.add("active");',
      '    document.body.style.overflow = "hidden";',
      '  }',
      '',
      '  function closeMobileMenu() {',
      '    hamburger.classList.remove("active");',
      '    mobileOverlay.classList.remove("active");',
      '    mobileMenu.classList.remove("active");',
      '    document.body.style.overflow = "";',
      '  }',
      '',
      '  hamburger.addEventListener("click", function() {',
      '    if (mobileMenu.classList.contains("active")) {',
      '      closeMobileMenu();',
      '    } else {',
      '      openMobileMenu();',
      '    }',
      '  });',
      '',
      '  mobileOverlay.addEventListener("click", closeMobileMenu);',
      '  mobileClose.addEventListener("click", closeMobileMenu);',
      '',
      '  // Escape key closes mobile menu',
      '  document.addEventListener("keydown", function(e) {',
      '    if (e.key === "Escape") {',
      '      closeMobileMenu();',
      '    }',
      '  });',
      '',
      '  // Window resize – close mobile menu if width > 992',
      '  window.addEventListener("resize", function() {',
      '    if (window.innerWidth > 992) {',
      '      closeMobileMenu();',
      '    }',
      '  });',
      '',
      '  // Mobile dropdown accordion toggles',
      '  var mobileToggles = document.querySelectorAll(".mobile-dropdown-toggle");',
      '  for (var i = 0; i < mobileToggles.length; i++) {',
      '    mobileToggles[i].addEventListener("click", function(e) {',
      '      var targetId = this.getAttribute("data-target");',
      '      var submenu = document.getElementById(targetId);',
      '      if (submenu) {',
      '        submenu.classList.toggle("active");',
      '        var chevron = this.querySelector(".fa-chevron-down");',
      '        if (chevron) {',
      '          if (submenu.classList.contains("active")) {',
      '            chevron.style.transform = "rotate(180deg)";',
      '          } else {',
      '            chevron.style.transform = "rotate(0deg)";',
      '          }',
      '        }',
      '      }',
      '    });',
      '  }',
      '',
      '  // Desktop dropdown – prevent default on dropdown parent links',
      '  var dropdownParents = document.querySelectorAll(".dropdown > .nav-link");',
      '  for (var j = 0; j < dropdownParents.length; j++) {',
      '    dropdownParents[j].addEventListener("click", function(e) {',
      '      e.preventDefault();',
      '    });',
      '  }',
      '})();'
    ].join('\n');
    document.body.appendChild(script);
  }

  // ═══════════════════════════════════════════════════════
  // DOM-ready injection
  // ═══════════════════════════════════════════════════════
  function init() {
    injectNavbar();
    injectScript();
    window.__smaNavbarLoaded = true;
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
